version: '3'
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  database:
    driver: local
  bundle:
    driver: local
